actions = {
    "Solo",
    "track 3",
    "shift",
    "slow",
    "now",
    "Mute",
    "Arm",
    "Play",
    "Pause",
    "Stop",
    "continue",
    "resume",
    "Control 1",
    "Control 2",
    "Control 3",
    "Control 4",
    "Control 5",
    "Control 6",
    "Control 7",
    "Control 8",
    "Map 1",
    "Map 2",
    "Map 3",
    "Map 4",
    "Map 5",
    "Map 6",
    "Map 7",
    "Map 8",
    "Map",
    "Listen",
    "Delete Map 1",
    "Delete Map 2",
    "Delete Map 3",
    "Delete Map 4",
    "Delete Map 5",
    "Delete Map 6",
    "Delete Map 7",
    "Delete Map 8",
    "Min Range",
    "Max Range",
    "search device",
    "Hey asa",
    "Device",
    "Device Chain",
    "View Clip",
    "delete device",
    "Arranger",
    "Session",

}